### ISSUE TITLE
Thread does not shutdown when get returns

### ISSUE THREAD

**Issue by ieee8023** [AcademicTorrents/at-python#23]
With this script:

```
import academictorrents as at
import sys, os
at.get(sys.argv[1],datastore="/network/data1/academictorrents-datastore/")
```
I get this error:
```
$ python download.py 9b13183dc4d60676b773c9e2cd6de5e5542cee9a
Torrent name: nf_prize_dataset.tar.gz, Size: 697.55MB
Checking for pieces on disk: |██████████| 100.0% 
Found 0 finished pieces out of 1331 total pieces.
Downloading to /network/data1/academictorrents-datastore/nf_prize_dataset.tar.gz
BT:1, Web:1 |██████████| 100.0% (6335.83kB/s)
 Download Complete!
Exception in thread Thread-1 (most likely raised during interpreter shutdown):Exception in thread Thread-28 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/network/home/cohenjos/.local/lib/python2.7/site-packages/academictorrents/Tracker.py", line 27, in run
  File "/network/home/cohenjos/.local/lib/python2.7/site-packages/academictorrents/Tracker.py", line 202, in scrape_udp
  File "/network/home/cohenjos/.local/lib/python2.7/site-packages/academictorrents/Tracker.py", line 176, in send_msg
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'timeout'

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/network/home/cohenjos/.local/lib/python2.7/site-packages/academictorrents/PeerManager.py", line 65, in run
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by mweiss17** [comment]
This is fixed here: https://github.com/AcademicTorrents/at-python/commit/2f61e60803dbc1ff88e3418d1d6e682a2004c06d

There were a few problems with how I was handling the threads. 

First, they shouldn't be daemons, which wasn't really bad but irrelevant. Auxiliary threads should exit before the main thread in this application. 

Second, the synchronized queues I was using to pass data to the threads were blocking. I added a timeout of 1 second to them, now we can request_stop to finish execution of the thread and block the main thread's execution with .join.
