### ISSUE TITLE
pip install bug

### ISSUE THREAD

**Issue by ahundt** [AcademicTorrents/at-python#3]
There appears to be some pip installation bugs, though it works with `pip2`:

```
) pip install academictorrents
Collecting academictorrents
  Using cached https://files.pythonhosted.org/packages/85/b8/276d72e19330981d48df6b6480fa975e10d9a80f0f3490d8dcab65454005/academictorrents-2.0.21.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9f/jr_p974d3j318tmvrfkjl55w0000gp/T/pip-install-fd55gdv7/academictorrents/setup.py", line 7, in <module>
        with open('LICENSE') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9f/jr_p974d3j318tmvrfkjl55w0000gp/T/pip-install-fd55gdv7/academictorrents/
-> [1]
) pip3 install academictorrents
Collecting academictorrents
  Using cached https://files.pythonhosted.org/packages/85/b8/276d72e19330981d48df6b6480fa975e10d9a80f0f3490d8dcab65454005/academictorrents-2.0.21.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9f/jr_p974d3j318tmvrfkjl55w0000gp/T/pip-install-l4oioj01/academictorrents/setup.py", line 7, in <module>
        with open('LICENSE') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9f/jr_p974d3j318tmvrfkjl55w0000gp/T/pip-install-l4oioj01/academictorrents/
-> [1]
) pip2 install academictorrents
Collecting academictorrents
  Downloading https://files.pythonhosted.org/packages/64/44/74e4de0b1ee76d252b829d5d651c724f2a3f72de6dab512f347b4994b696/academictorrents-2.0.21-py2-none-any.whl
Collecting PyPubSub==3.3.0 (from academictorrents)
  Downloading https://files.pythonhosted.org/packages/95/5a/1801be1a63af9250e79b8941a37b88e3ca0d660b880b9862fe9016ae6a3a/PyPubSub-3.3.0.zip (87kB)
    100% |████████████████████████████████| 92kB 3.0MB/s
Collecting future==0.16.0 (from academictorrents)
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 9.8MB/s
Collecting bencode.py==2.0.0 (from academictorrents)
  Downloading https://files.pythonhosted.org/packages/1f/09/cda159542fe188706de49734e26522c360affe79f8dcf01e807f72cdfc7f/bencode.py-2.0.0-py2.py3-none-any.whl
Collecting bitstring==3.1.5 (from academictorrents)
  Downloading https://files.pythonhosted.org/packages/f3/e5/dfe4c49c93d174a5fd807ed307d3a3f38c6b3e140972945f81a5f5578ca7/bitstring-3.1.5.zip (624kB)
    100% |████████████████████████████████| 624kB 10.7MB/s
Collecting requests==2.7.0 (from academictorrents)
  Downloading https://files.pythonhosted.org/packages/26/ff/c71b3943bebdd9f7ceb9e137296370587eb0b33fe2eb3732ae168bc45204/requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 12.1MB/s
Building wheels for collected packages: PyPubSub, future, bitstring
  Running setup.py bdist_wheel for PyPubSub ... done
  Stored in directory: /Users/athundt/Library/Caches/pip/wheels/94/da/6e/2127e2253ef98b9b98b625e78f5158dd66966a5cc9f1d1478b
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /Users/athundt/Library/Caches/pip/wheels/bf/c9/a3/c538d90ef17cf7823fa51fc701a7a7a910a80f6a405bf15b1a
  Running setup.py bdist_wheel for bitstring ... done
  Stored in directory: /Users/athundt/Library/Caches/pip/wheels/2d/29/47/179175c4ddff694032837432ae45c04c6bf93e4b01c23fb5b3
Successfully built PyPubSub future bitstring
internetarchive 1.8.2.dev1 has requirement requests<3.0.0,>=2.9.1, but you'll have requests 2.7.0 which is incompatible.
Installing collected packages: PyPubSub, future, bencode.py, bitstring, requests, academictorrents
  Found existing installation: requests 2.20.0
    Uninstalling requests-2.20.0:
      Successfully uninstalled requests-2.20.0
Successfully installed PyPubSub-3.3.0 academictorrents-2.0.21 bencode.py-2.0.0 bitstring-3.1.5 future-0.16.0 requests-2.18.4
```

**Comment by mweiss17** [comment]
Thanks @ahundt for the heads up! I'll take a look at this shortly and get back to you.

**Comment by mweiss17** [comment]
@ahundt 
This issue has been resolved in the newest version of the AcademicTorrents package out on PyPi and Github, version 2.0.27.

Thanks for letting me know about it!
